### ISSUE TITLE
Needed to install broccoli-stew

### ISSUE THREAD

**Issue by alexlafroscia** [EmberGrep/ember-cli-eg-code-highlight#6]
After installing `ember-highlight-js`, I got errors about `broccoli-stew` not being installed, and needed to add it to the project's dependencies.  It would be nice if the package could handle that so that I could keep it out of my `package.json`.

**Comment by rtablada** [comment]
Will need to check in on this, just pulled in a large refactor from @stefanpenner and may have a stray dep.

**Comment by sukima** [comment]
Confirmed:

```console
version: 0.2.0-beta.1
Cannot find module 'broccoli-stew'
Error: Cannot find module 'broccoli-stew'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/suki/source/SeeClickFix/test-select-picker/node_modules/ember-highlight-js/index.js:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by SamvelRaja** [comment]
Kindly publish this change in `npm` with a minor version bump
This making the addon unusable

**Comment by paultannenbaum** [comment]
@rtablada and anyone else with this problem, until they update the npm package to pull down the latest from master, you can point your `package.json` dependency at this repo:

`"highlightjs": "EmberGrep/ember-cli-eg-code-highlight"`
